Idvalidation
Fullstack-Alfanar/Aimanzi-Homework pull request #2
Opened 2022-04-11 14:47 UTC by aimanzi

ID validation homework

2022-04-12 19:17 UTC, EliasSalom requested changes
please review my comments and fix all the issues and push a new code

2022-04-12 19:17 UTC, EliasSalom commented on Email validation/java/script.js
> +        for (let x = 0; x <numbers.length; x++) {
there is a `number` variable and I think you forgot to define it, please review the code again, I received a `numbers is not defined` error

2022-04-12 19:17 UTC, EliasSalom commented on I.D Validation/index.html
> +    <div>Enter your full name :<input type="text" placeholder="Name"  id="name"></div><br>
I think I have been saying many times that we are never let the text free, the text must be inside some element, please review the code again and fix this issue

2022-04-13 06:02 UTC, aimanzi commented on I.D Validation/index.html
> +    <div>Enter your full name :<input type="text" placeholder="Name"  id="name"></div><br>
i have fixed thr uncorrect issues by adding <label> element before the Text

2022-04-13 06:17 UTC, aimanzi commented on Email validation/java/script.js
> +        for (let x = 0; x <numbers.length; x++) {
i have fix the issues ,
the variable "numbers" wase undefined ;

2022-04-13 11:39 UTC, EliasSalom approved these changes
good work

2022-04-13 11:39 UTC, merged